<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="3032" started-at="2016-12-01T11:47:19Z" finished-at="2016-12-01T11:47:22Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="3032" started-at="2016-12-01T11:47:19Z" finished-at="2016-12-01T11:47:22Z">
      <class name="com.ttfc.soa.dubbo.provider.service.TestBranch">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.ttfc.soa.dubbo.provider.service.TestBranch@50de0926]" name="beforeTest" is-config="true" duration-ms="8" started-at="2016-12-01T19:47:19Z" finished-at="2016-12-01T19:47:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="springTestContextPrepareTestInstance()[pri:0, instance:com.ttfc.soa.dubbo.provider.service.TestBranch@50de0926]" name="springTestContextPrepareTestInstance" is-config="true" duration-ms="2951" started-at="2016-12-01T19:47:19Z" depends-on-methods="org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextBeforeTestClass" finished-at="2016-12-01T19:47:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextPrepareTestInstance -->
        <test-method status="PASS" signature="springTestContextBeforeTestClass()[pri:0, instance:com.ttfc.soa.dubbo.provider.service.TestBranch@50de0926]" name="springTestContextBeforeTestClass" is-config="true" duration-ms="0" started-at="2016-12-01T19:47:19Z" finished-at="2016-12-01T19:47:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestClass -->
        <test-method status="PASS" signature="springTestContextBeforeTestMethod(java.lang.reflect.Method)[pri:0, instance:com.ttfc.soa.dubbo.provider.service.TestBranch@50de0926]" name="springTestContextBeforeTestMethod" is-config="true" duration-ms="0" started-at="2016-12-01T19:47:21Z" finished-at="2016-12-01T19:47:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[void com.ttfc.soa.dubbo.provider.service.TestBranch.testGetBranchCompanys()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestMethod -->
        <test-method status="FAIL" signature="testGetBranchCompanys()[pri:0, instance:com.ttfc.soa.dubbo.provider.service.TestBranch@50de0926]" name="testGetBranchCompanys" duration-ms="60" started-at="2016-12-01T19:47:21Z" finished-at="2016-12-01T19:47:22Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<0> but was:<4>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<0> but was:<4>
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:245)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:252)
	at com.ttfc.soa.dubbo.provider.service.TestBranch.testGetBranchCompanys(TestBranch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:189)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:170)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:201)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:642)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetBranchCompanys -->
        <test-method status="PASS" signature="springTestContextAfterTestClass()[pri:0, instance:com.ttfc.soa.dubbo.provider.service.TestBranch@50de0926]" name="springTestContextAfterTestClass" is-config="true" duration-ms="1" started-at="2016-12-01T19:47:22Z" finished-at="2016-12-01T19:47:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestClass -->
        <test-method status="PASS" signature="springTestContextAfterTestMethod(java.lang.reflect.Method)[pri:0, instance:com.ttfc.soa.dubbo.provider.service.TestBranch@50de0926]" name="springTestContextAfterTestMethod" is-config="true" duration-ms="0" started-at="2016-12-01T19:47:22Z" finished-at="2016-12-01T19:47:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[void com.ttfc.soa.dubbo.provider.service.TestBranch.testGetBranchCompanys()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestMethod -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.ttfc.soa.dubbo.provider.service.TestBranch@50de0926]" name="afterTest" is-config="true" duration-ms="0" started-at="2016-12-01T19:47:22Z" finished-at="2016-12-01T19:47:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.ttfc.soa.dubbo.provider.service.TestBranch -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
